- name: Good First Issue
  color: "c3c4c7"
  description: "A great place to start if you're new to contributing"
- name: First-time Contributor
  color: "c3c4c7"
  description: "Pull request opened by a first-time contributor"

- name: "[Priority] Low"
  color: "907300"
  description: "This issue/pull request is not immediate"
- name: "[Priority] High"
  color: "b26200"
  description: "This issue/pull request needs resolving before the next release"
- name: "[Priority] Critical"
  color: "d63638"
  description: "This issue/pull request needs resolving immediately, likely followed by a hot-fix"

- name: "[Status] In Progress"
  color: "005042"
  description: "Tracking issues with work in progress"
- name: "[Status] Needs Info"
  color: "005042"
  description: "Tracking issues with follow-up required in order to be actionable"
- name: "[Status] Won't Fix"
  color: "005042"
  description: "Issues/PRs we will (likely) not implement"
- name: "[Status] Waiting"
  color: "005042"
  description: "Issues/PRs that are on hold"
- name: "[Status] Do Not Merge"
  color: "005042"
  description: "Issues/PRs that should not be merged (yet)"
- name: "[Status] Needs Review"
  color: "006753"
  description: "Tracking pull requests that need another set of eyes"

- name: "[Type] a11y"
  color: "008a20"
  description: "Changes that impact accessibility"
- name: "[Type] i18n"
  color: "907300"
- name: "[Type] Enhancement"
  color: "984a9c"
  description: "Something new that adds functionality"
- name: "[Type] Bug"
  color: "b32d2e"
- name: "[Type] WP Core Bug"
  color: "006088"
- name: "[Type] Maintenance"
  color: "704000"
  description: "Minor file cleanup and organization tasks"
- name: "[Type] Tooling"
  color: "2271b1"
  description: "Issues related to development tooling"
- name: "[Type] Tests"
  color: "646970"
  description: "Issues related the testing suite; i.e. Cypress, Jest, PHPUnit, etc"
- name: "[Type] Code Quality"
  color: "2271b1"
  description: "Issues related to improving the quality of our code"
- name: "[Type] Documention"
  color: "2271b1"
  description: "Issues related to improving documention"
