version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-Core"
exclude_patterns:
  - ".dev/config/"
  - ".dev/deploy-scripts/"
  - ".dev/tests/"
  - ".dev/assets/shared/js/frontend/vendor/"
  - "includes/classes/class-tgm-plugin-activation.php"
