name: Publish Coverage to SPAQ

on:
  push:
    branches:
      - try-publish-coverage

jobs:
  publish_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run Coverage Report
        run: |
          npm ci
          npm run test:js:coverage
      - name: Downloading SPAQ-CLI and making executable.
        shell: bash
        run: |
          curl https://assets.spaq.gdcorp.tools/spaq-cli-linux-x64_v1 -o spaq-cli
          chmod +x spaq-cli
      - name: Publishing Code Coverage report to SPAQ.
        shell: bash
        run: |
          ./spaq-cli publish-coverage file \
            --file=./coverage/lcov.info \
            --type=lcov \
            --service=4185 \
            --repo=${{ github.repository }} \
            --git-sha=${{ github.sha }}
