name: Publish Coverage to SPAQ

on:
  push:
    branches:
      - try-publish-coverage

jobs:
  publish_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout Private Action
        uses: actions/checkout@v3
        with:
          repository: gdcorp-wordpress/spaq-publish-coverage
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./.github/actions/spaq-publish-coverage
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test:js:coverage
      - uses: ./.github/actions/spaq-publish-coverage
        with:
          coverage-file: 'coverage/lcov.info'
          coverage-type: 'lcov'
          service-id: 4185
